# NumPy
> Numerical Python

Advantages of NumPy Arrays:
1. Allows several Mathematical Operators
2. Faster operations

In [3]:
import numpy as np

# list vs NumPy - Time taken

from time import process_time

pythonList = [i for i in range(10000)]
startTime = process_time()
pythonList = [i + 5 for i in pythonList]
endTime = process_time()
print(endTime - startTime)

0.0


In [5]:
npArray = np.array([i for i in range(10000)])
startTime = process_time()
npArray += 5
endTime = process_time()
print(endTime - startTime)

0.0


## NumPy Arrays

In [7]:
listOne = [1,2,3,4,5]
type(listOne)

npArray = np.array([1,2,3,4,5])
type(npArray)


numpy.ndarray

Multidimensional array

In [12]:
mdArr = np.array([(1,2,3,4), (5,6,7,8)])
print(mdArr)
mdArr.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Initial Placeholders in NumPy

In [13]:
zerosArr = np.zeros((4, 5))
print(zerosArr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
onesArr = np.ones((3,3))
print(onesArr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array filled with particular value
zArr = np.full((5,4), 5)
print(zArr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# identity matrix
iMat = np.eye(5)
print(iMat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
# arrays with random values

# random floats
randomFloats = np.random.random((3,4))
print(randomFloats)
# random ints within a specific range
randomInts = np.random.randint(10, 100, (3,5))
print(randomInts)

[[0.26498164 0.83938572 0.94695572 0.48415816]
 [0.847097   0.93972709 0.44351517 0.12139963]
 [0.85026443 0.01422356 0.72179767 0.27339586]]
[[44 56 69 93 64]
 [49 21 70 43 53]
 [79 14 94 65 80]]


In [21]:
# evenly spcaed values
evenVal = np.linspace(10, 30, 6)
print(evenVal)

[10. 14. 18. 22. 26. 30.]


In [22]:
# evenly spcaed values specifing a step
evenStepVals = np.arange(10,30, 5)
print(evenStepVals)

[10 15 20 25]


In [23]:
# convert list into numpy array
pyList = [10, 20, 30, 30, 10, 40]

npArray = np.asarray(pyList)
print(npArray)
type(npArray)

[10 20 30 30 10 40]


numpy.ndarray

### Analysing NumPy arrays

In [5]:
# array dimension
print(randomInts.shape)

(3, 5)


In [6]:
# number of dimensions
print(randomInts.ndim)

2


In [7]:
# number of elements in array
print(randomInts.size)

15


In [8]:
# checking data type of values in the array
print(randomInts.dtype)

int32


## Mathematical operations on a NP array

In [9]:
listOne = [1,2,3,4,5]
listTwo = [6,7,8,9,10]

print(listOne + listTwo) # conactenates two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [15]:
npArrOne = np.random.randint(0, 10, (3, 3))
npArrTwo = np.random.randint(0, 10, (3, 3))

# adding 2 np arrays results in adding the values from each index togheter
print(npArrOne + npArrTwo)

[[11 14  3]
 [12 10 11]
 [15 10  8]]


In [17]:
# more mathematical operations
print(npArrOne * npArrTwo)
print(npArrOne / npArrTwo)

[[30 45  2]
 [32 16 24]
 [54 24  7]]
[[0.83333333 1.8        2.        ]
 [0.5        0.25       0.375     ]
 [1.5        1.5        7.        ]]


In [19]:
# mathematical operations on 2 NumPy arrays using provided functions

print(np.add(npArrOne, npArrTwo))
print(np.subtract(npArrOne, npArrTwo))
print(np.multiply(npArrOne, npArrTwo))
print(np.divide(npArrOne, npArrTwo))

[[11 14  3]
 [12 10 11]
 [15 10  8]]
[[-1  4  1]
 [-4 -6 -5]
 [ 3  2  6]]
[[30 45  2]
 [32 16 24]
 [54 24  7]]
[[0.83333333 1.8        2.        ]
 [0.5        0.25       0.375     ]
 [1.5        1.5        7.        ]]


## Array Manipulation

In [20]:
npArr = np.random.randint(0, 10, (2, 3))
print(npArr)
print(npArr.shape)

[[8 5 3]
 [8 0 3]]
(2, 3)


### Transpose
* creating the transponse of the matrix => reversing the shape of the matrix

In [21]:
trans = np.transpose(npArr)
print(trans)
print(trans.shape)

[[8 8]
 [5 0]
 [3 3]]
(3, 2)


In [22]:
# another transpose solution
secondTrans = npArr.T
print(secondTrans)
print(secondTrans.shape)

[[8 8]
 [5 0]
 [3 3]]
(3, 2)


### Reshaping

In [23]:
npArrRe = np.random.randint(0, 10, (2, 3))
print(npArrRe)
print(npArrRe.shape)

[[7 6 0]
 [9 6 0]]
(2, 3)


In [25]:
npArrReB = npArrRe.reshape(3,2)
print(npArrReB)
print(npArrReB.shape)

[[7 6]
 [0 9]
 [6 0]]
(3, 2)
