In [1]:
import numpy as np

## Creating Matrices using Numpy

In [6]:
matrix_1 = np.array([
    [2, 3],
    [6, 7]
])

print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([
    [10,35,45],
    [50,64,80],
    [20,15,90]
])

print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [7]:
matrix_2.shape

(3, 3)

Creating Matrices with random values

In [8]:
random_matrix = np.random.rand(3,3) # creates a 3x3 Matrix with random values between 0-1
print(random_matrix)

[[0.57222334 0.34282463 0.25470791]
 [0.18016977 0.48961254 0.55628775]
 [0.60970592 0.85526676 0.27817785]]


In [10]:
rand_int_matrix = np.random.randint(100, size=(4,5))

print(rand_int_matrix)

[[33 23 78 72 70]
 [65 26 75 57 55]
 [80 41 18 65 21]
 [14 57 18  2 80]]


## Matrices with all values as 1

In [12]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
matrix_3 = np.ones((5,7), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


## Null Matrix

In [15]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Identity Matrix
* all diagonal values 1 and the rest remain 0

In [17]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Transpose of a Matrix

In [19]:
# random matrix
a = np.random.randint(100, size=(4,5))
print(a)

[[46 51 60 15 62]
 [43 38 63 56 29]
 [66 15 57 11  4]
 [ 6 20 17 84 83]]


In [20]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[46 43 66  6]
 [51 38 15 20]
 [60 63 57 17]
 [15 56 11 84]
 [62 29  4 83]]
