# Matrix operations in python

In [1]:
import numpy as np

## Matrix Addition
* can be added only if they have the same shape

In [6]:
a = np.array([
    [2,3],
    [4,5]
])

b = np.array([
    [6,7],
    [8,9]
])

print(a, a.shape)
print(b, b.shape)

[[2 3]
 [4 5]] (2, 2)
[[6 7]
 [8 9]] (2, 2)


In [7]:
abSum = a + b

print(abSum)

[[ 8 10]
 [12 14]]


In [12]:
# creating 2 similarly shaped matrices with randomn values
mx_1 = np.random.randint(10, size=(3,3))
mx_2 = np.random.randint(20, size=(3,3))

print(mx_1)
print(mx_2)

[[6 2 0]
 [7 7 8]
 [6 7 1]]
[[ 2 12  6]
 [18  7  2]
 [15 13 18]]


In [11]:
mxsSum = np.add(mx_1, mx_2)

print(mxsSum)

[[16  1  9]
 [ 3  6 11]
 [15 10 20]]


In [13]:
# creating 2 matrices with randomn values with diferent shapes
mx_1_2 = np.random.randint(10, size=(3,3))
mx_2_2 = np.random.randint(20, size=(3,4))

sum2 = np.add(mx_1_2,mx_2_2)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

***adding different shaped matrices will always throw an error***

## Matrix Substraction

In [15]:
a = np.array([
    [2,3],
    [4,5]
])

b = np.array([
    [6,7],
    [8,9]
])

difference = a - b

print(difference)

[[-4 -4]
 [-4 -4]]


In [18]:
# creating 2 similarly shaped matrices with randomn values
mx_1 = np.random.randint(10, size=(3,3))
mx_2 = np.random.randint(20, size=(3,3))

print(mx_1)
print(mx_2)

mx_diff = np.subtract(mx_1, mx_2)
print(mx_diff)

[[0 7 1]
 [2 2 8]
 [0 5 1]]
[[ 4 13  6]
 [ 1  1 10]
 [14  8  9]]
[[ -4  -6  -5]
 [  1   1  -2]
 [-14  -3  -8]]


## Multiplying a Matrix by a Scalar

In [19]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[0 5 0 0]
 [9 3 7 8]
 [7 2 1 0]
 [4 0 9 3]]


In [20]:
scalar_matrix_product = np.multiply(x,y)
print(scalar_matrix_product)

[[ 0 25  0  0]
 [45 15 35 40]
 [35 10  5  0]
 [20  0 45 15]]


## Multiplying 2 Matrices
***Row-Wise Multiplication***

In [22]:
mx_3 = np.random.randint(10, size=(3,3))
mx_4 = np.random.randint(20, size=(3,4))

print(mx_3)
print(mx_4)

[[8 6 2]
 [3 2 7]
 [5 7 6]]
[[ 6 18 11 19]
 [ 7 13 16  2]
 [ 4 14  2  0]]


In [24]:
mxs_product = np.dot(mx_3,mx_4)

print(mxs_product, mxs_product.shape)

[[ 98 250 188 164]
 [ 60 178  79  61]
 [103 265 179 109]] (3, 4)


***Element-Wise Multiplication***

In [26]:
mx_5 = np.random.randint(10, size=(3,3))
mx_6 = np.random.randint(20, size=(3,3))

print(mx_5)
print(mx_6)

[[0 9 1]
 [0 6 6]
 [7 3 8]]
[[ 1  7  3]
 [16  1 18]
 [16  3  9]]


In [27]:
element_multiply = np.multiply(mx_5, mx_6)
print(element_multiply)

[[  0  63   3]
 [  0   6 108]
 [112   9  72]]


In [30]:
print(element_multiply[2][1])

9
